<a href="https://colab.research.google.com/github/arnavjune2/TensorFlow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.7.0'

## Tensor constant
Tensor: multi dim array

In [3]:
const = tf.constant(43)
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [4]:
const.numpy()

43

JAX: built on Numpy but it supports CUDA

In [5]:
# const of specific datatype
const = tf.constant(43, dtype= tf.float32)
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [7]:
#const matrix
const_mat = tf.constant([[1,3],[4,6]], dtype= tf.float32)
const_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 6.]], dtype=float32)>

In [9]:
const_mat.shape

TensorShape([2, 2])

In [11]:
const_mat[1][0].numpy()

4.0

## Commonly used methods

In [16]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
-1*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [18]:
6*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [20]:
tf.zeros(shape=(5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## add operations

In [24]:
const1 = tf.constant([[1,2,3],[4,5,6]])
const2 = tf.constant([[5,5,5],[9,5,6]])
const1 + cosnt2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6,  7,  8],
       [13, 10, 12]], dtype=int32)>

In [25]:
tf.add(const1, const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6,  7,  8],
       [13, 10, 12]], dtype=int32)>

## Random const

In [26]:
tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.8871031 ,  2.6439986 ],
       [-0.3291627 , -0.33135644]], dtype=float32)>

In [30]:
tf.random.uniform(shape=(2,2), minval=0, maxval=20 )

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14.655874 , 14.891632 ],
       [12.146077 ,  1.8541884]], dtype=float32)>

Variables

In [34]:
var1 = tf.Variable(45)
var_mat =  tf.Variable([1,2,3,5],[6,5,4,3])

In [35]:
var_mat

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 5], dtype=int32)>

In [36]:
var1 = tf.Variable(43)
var1.assign(32) #mutable

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=32>

## reshaping operation

In [39]:
tensor= tf.Variable([[1,2,3],[4,5,6]])
tensor.shape

TensorShape([2, 3])

In [41]:
tf.reshape(tensor, [1,-1])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [43]:
tf.reshape(tensor, [3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

other mathematical ops

In [47]:
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [48]:
tf.square(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

## broadcasting in TF

In [49]:
scaler = 4

scaler* tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]], dtype=int32)>

In [50]:
scaler + tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)>

In [51]:
scaler - tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  2,  1],
       [ 0, -1, -2]], dtype=int32)>

##matrix multiplicatiion

In [58]:
t1 = tensor
t2 = tf.square(tensor)

In [61]:
t1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [62]:
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

rule: columns of t1=columns of t2 then only matrix multiplication will take place

In [57]:
tf.matmul(t1, t2)

InvalidArgumentError: ignored

In [63]:
tf.matmul(t1, tf.transpose(t2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36, 174],
       [ 78, 405]], dtype=int32)>

In [65]:
#alternative of the above 
t1 @ tf.transpose(t2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36, 174],
       [ 78, 405]], dtype=int32)>

In [66]:
#for element wise multiplication
t1 * t2  #shape should be same

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)>

## casting method in tf to change the data type
can be use in quantizing the model to save the space

In [69]:
t2.dtype

tf.int32

In [70]:
tf.cast(t2, dtype= tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

## Raaged tensors
nested variable length arrrays

In [73]:
ragged = tf.ragged.constant([[1,2,3,4,5,6],[1],[135,1]])

In [74]:
ragged.shape

TensorShape([3, None])

## Squared difference of tensors

In [78]:
t1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [79]:
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [80]:
tf.math.squared_difference(t1,t2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  0,   4,  36],
       [144, 400, 900]], dtype=int32)>

## Mean

In [88]:
print(tf.reduce_mean(t1).numpy())
print(tf.reduce_mean(t1, axis=0).numpy()) #row wise mean
print(tf.reduce_mean(t1, axis=1).numpy()) #column wise mean

3
[2 3 4]
[2 5]


## Checkponting to restore the matrix values

In [89]:
var1 = tf.Variable(5*tf.ones((5,5)))
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

In [90]:
ckpt = tf.train.Checkpoint(var=var1)
savepath = ckpt.save("./vars.ckpt")

In [95]:
var1.assign(tf.zeros((5,5))) #changing the values of var1

<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [96]:
ckpt.restore(savepath) #restoring the older values 
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

## tf.function

$z = x^3 *6 + y^3$

In [102]:
def f1(x,y):
  input_Var= tf.multiply(x**3,6) + y**3
  return tf.reduce_mean(input_tensor=input_Var)

In [103]:
func = tf.function(f1) #it will now use f1 function as a tensorflow function

In [104]:
x = tf.constant([3.,-4.])
y= tf.constant([1.,4.])

In [105]:
f1(x,y) ##using simpole python function

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [107]:
func(x,y) ##more optimized

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [108]:
@tf.function ## tf decorator function
def f2(x,y):
  input_Var= tf.multiply(x**3,6) + y**3
  return tf.reduce_mean(input_tensor=input_Var)