<a href="https://colab.research.google.com/github/arnavjune2/TensorFlow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.7.0'

## Tensor constant
Tensor: multi dim array

In [3]:
const = tf.constant(43)
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [4]:
const.numpy()

43

JAX: built on Numpy but it supports CUDA

In [5]:
# const of specific datatype
const = tf.constant(43, dtype= tf.float32)
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [7]:
#const matrix
const_mat = tf.constant([[1,3],[4,6]], dtype= tf.float32)
const_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 6.]], dtype=float32)>

In [9]:
const_mat.shape

TensorShape([2, 2])

In [11]:
const_mat[1][0].numpy()

4.0

## Commonly used methods

In [16]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
-1*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [18]:
6*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [20]:
tf.zeros(shape=(5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## add operations

In [24]:
const1 = tf.constant([[1,2,3],[4,5,6]])
const2 = tf.constant([[5,5,5],[9,5,6]])
const1 + cosnt2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6,  7,  8],
       [13, 10, 12]], dtype=int32)>

In [25]:
tf.add(const1, const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6,  7,  8],
       [13, 10, 12]], dtype=int32)>

## Random const

In [26]:
tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.8871031 ,  2.6439986 ],
       [-0.3291627 , -0.33135644]], dtype=float32)>

In [30]:
tf.random.uniform(shape=(2,2), minval=0, maxval=20 )

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14.655874 , 14.891632 ],
       [12.146077 ,  1.8541884]], dtype=float32)>

Variables

In [34]:
var1 = tf.Variable(45)
var_mat =  tf.Variable([1,2,3,5],[6,5,4,3])

In [35]:
var_mat

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 5], dtype=int32)>

In [36]:
var1 = tf.Variable(43)
var1.assign(32) #mutable

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=32>

## reshaping operation

In [39]:
tensor= tf.Variable([[1,2,3],[4,5,6]])
tensor.shape

TensorShape([2, 3])

In [41]:
tf.reshape(tensor, [1,-1])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [43]:
tf.reshape(tensor, [3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

other mathematical ops

In [44]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>

In [46]:
tf.square(var1)

<tf.Tensor: shape=(), dtype=int32, numpy=1024>