<a href="https://colab.research.google.com/github/arnavjune2/TensorFlow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.7.0'

## Tensor constant
Tensor: multi dim array

In [3]:
const = tf.constant(43)
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [4]:
const.numpy()

43

JAX: built on Numpy but it supports CUDA

In [5]:
# const of specific datatype
const = tf.constant(43, dtype= tf.float32)
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [7]:
#const matrix
const_mat = tf.constant([[1,3],[4,6]], dtype= tf.float32)
const_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 6.]], dtype=float32)>

In [9]:
const_mat.shape

TensorShape([2, 2])

In [11]:
const_mat[1][0].numpy()

4.0

## Commonly used methods

In [16]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
-1*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [18]:
6*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [20]:
tf.zeros(shape=(5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>